apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: default
spec:
  encryptedData:
    credentials.json: AgBQEGIMspSfu0WX53PVDTmG6SJUSWG4J2pmGT8G5pYQXzRwNt7ClPDpdRC1GfKxxOY00M7ygv1xg8+qAKqNPUq2ez5kxYonhFHxCKay8GP9VNvit4YIxKvLfQyWNNkKA910YRLoPs6TA4LFL9DUMAf8f7G4R/tr0mI5biMLu0dlZdOT68eLGBtcOBDMm/fwvmr4bNy/4wjOcML7K7f/5BRyFPZEi0ntoAv6yu4BAmd0dIMooU5nDqbx32WJOPg2yeVQOHkYrqEU8lPwny9JKg+U89ePrCDdakg1AwJJdYiqjQY8EoEZZ8jiMur/OceCTN7X+NgF/9pZV1fAC7dH1oFu/ZIWXNx8vis3uyuVthDZ7lEWVVy0y0YW7CeXb7OUhrpSHppBvMBWSf4gkx10UT/KlVzUPd0lHeCTKx6jRUErdQXqOAgcxV12BtN6wBFoE3S8mfdzvrZf8XQnBEUdUz4p5xZduBCOovGkbWGuQzIOEmQgE/nCjFLPFetCtYFvZIRec43yK2dbe8d6m7oQv/KcgH47sGtQcY2FHkJDB5vBZ4wNOdee51WKsYYmbEYZ+AZig/jOMttxg0EodQ+xlUeNPCyTLqgjfS5GQFRBwPfMddRpT0KdG4MoqoP78hTzSbe1erv9KRsuM1tjjh465zyWt0hioy9ctAJ/GQhPlNgVh+Eq3h7GbTSPucolJEEHcTq8whFyI6V4j0W+8ehnXJTv9wLqMvGaGgw6oNxTqc3xTI1UlzdG6/elIeiRu44qu4fQOxrxnZg9Fd0XaOuD7QY1Sr03MqoHDBX6XAFUUZ1DtsvVqGo28LyuCyoOs99GIRoN7GphFRy5FGJa5Qqyp6GFfyAN6L5FmusOcgF9e11l5MhgUQZ1XawbupKTFyTcB0zxLVagCgwZ9CLRN+74ax78/A==
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: default

